# Generated by Django 4.2.7 on 2024-07-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_carouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='business_strength/')),
                ('icon', models.ImageField(upload_to='business_strength/icons/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
