# Generated by Django 4.2.7 on 2024-07-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_career_headerimage_careerapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career_HeaderImage',
        ),
    ]
