# Generated by Django 4.2.7 on 2024-07-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Investor',
        ),
    ]
