# Generated by Django 4.2.7 on 2024-09-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='quote',
            field=models.TextField(max_length=200),
        ),
    ]
