# Generated by Django 4.2.7 on 2024-09-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_investor_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='quote',
            field=models.TextField(max_length=150),
        ),
    ]
