# Generated by Django 4.2.7 on 2024-09-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Chairman', 'Chairman'), ('MD', 'Managing Director')], default='Chairman', max_length=100),
        ),
    ]
