# Generated by Django 4.2.7 on 2024-10-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
